name: Snyk SAST Scan

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:

jobs:
  snyk:
    name: Run Snyk SAST Scan
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk  # Install Snyk CLI globally

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN
          snyk test --severity-threshold=high

      - name: Monitor and report to Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk monitor
